import { PasswordPolicy } from "../password-policy";
import { WebSocketConfig } from "../web-socket-config";
import { BaseResponse } from "./base-response";

export interface UserLoginResponse extends BaseResponse {
    ChangePassword: string,
    DepartmentId: number,
    Email: string,
    FirstName: string,
    IgnorePasswordExpiry: boolean,
    IsAdmin: boolean,
    IsLoginFailed: boolean,
    IsPasswordAutoGenerated: boolean,
    IsPasswordChangeRequired: boolean,
    IsPasswordExpired: boolean,
    LastLogin: string,
    LastName?: string,
    LoginName: string,
    Logo: string,
    MiddleName?: string,
    MobileNumber: string,
    Name: string,
    OTPValidationNeeded: boolean,
    SecureLoginImageUrl?: string,
    SecureLoginText?: string,
    TimeZoneId?: string,
    TimeZoneLocation?: string,
    Token: string,
    TypeOfUser: number,
    UserBelongsTo: string,
    UserBelongsToId?: string,
    UserId: number,
    UserMfaEnabled: boolean,
    UserPhotoPath: string,
    Actions: string[],
    PasswordPolicy: PasswordPolicy,
    Roles: string[],
    WebsocketConf: WebSocketConfig
}
